### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by o-leolleo** [leolleocomp/mongodb#2]

**Comment by tomassirio** [comment]
On it!

**Comment by o-leolleo** [comment]
Great! There you go! @tomassirio

**Comment by tomassirio** [comment]
There you go buddy [#3](https://github.com/leolleocomp/ansible-role-mongodb/pull/3)

I added an english file and one in spanish. I don't know any portuguese but... you know, old language and football rivalries

**Comment by o-leolleo** [comment]
I'll review it, thanks in advance! And don't worry, I think I can create an issue for the portuguese version :smile: .

**Comment by o-leolleo** [comment]
Closed by https://github.com/leolleocomp/ansible-role-mongodb/pull/3
